<?php
/**
 * ForecastTemperatureTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ForecastTemperatureTest Class Doc Comment
 *
 * @category    Class
 * @description ForecastTemperature
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ForecastTemperatureTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ForecastTemperature"
     */
    public function testForecastTemperature()
    {
    }

    /**
     * Test attribute "low"
     */
    public function testPropertyLow()
    {
    }

    /**
     * Test attribute "high"
     */
    public function testPropertyHigh()
    {
    }

    /**
     * Test attribute "morning"
     */
    public function testPropertyMorning()
    {
    }

    /**
     * Test attribute "day"
     */
    public function testPropertyDay()
    {
    }

    /**
     * Test attribute "evening"
     */
    public function testPropertyEvening()
    {
    }

    /**
     * Test attribute "night"
     */
    public function testPropertyNight()
    {
    }
}
