<?php
/**
 * ForecastTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ForecastTest Class Doc Comment
 *
 * @category    Class
 * @description Forecast
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ForecastTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Forecast"
     */
    public function testForecast()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "pressure"
     */
    public function testPropertyPressure()
    {
    }

    /**
     * Test attribute "humidity"
     */
    public function testPropertyHumidity()
    {
    }

    /**
     * Test attribute "wind_speed"
     */
    public function testPropertyWindSpeed()
    {
    }

    /**
     * Test attribute "clouds"
     */
    public function testPropertyClouds()
    {
    }

    /**
     * Test attribute "temperature"
     */
    public function testPropertyTemperature()
    {
    }

    /**
     * Test attribute "weather"
     */
    public function testPropertyWeather()
    {
    }
}
