<?php
/**
 * ZWaveApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ZWaveApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZWaveApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getLightingSummary
     *
     * .
     *
     */
    public function testGetLightingSummary()
    {
    }

    /**
     * Test case for getSwitchState
     *
     * .
     *
     */
    public function testGetSwitchState()
    {
    }

    /**
     * Test case for setDimmer
     *
     * .
     *
     */
    public function testSetDimmer()
    {
    }

    /**
     * Test case for setDimmerTimer
     *
     * .
     *
     */
    public function testSetDimmerTimer()
    {
    }

    /**
     * Test case for setSwitch
     *
     * .
     *
     */
    public function testSetSwitch()
    {
    }

    /**
     * Test case for setSwitchTimer
     *
     * .
     *
     */
    public function testSetSwitchTimer()
    {
    }
}
