/**
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Forecast (
  date: Option[DateTime] = None,
  pressure: Option[Double] = None,
  humidity: Option[Int] = None,
  windSpeed: Option[Double] = None,
  clouds: Option[Int] = None,
  temperature: Option[ForecastTemperature] = None,
  weather: Option[WeatherForecast] = None
) extends ApiModel


